"""create initial krushimitra schema

Revision ID: b0f7f5ee2eba
Revises: 
Create Date: 2026-09-25 11:08:49.477665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'b0f7f5ee2eba'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_table('farmer_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('village', sa.String(length=150), nullable=True),
    sa.Column('district', sa.String(length=150), nullable=True),
    sa.Column('state', sa.String(length=150), nullable=True),
    sa.Column('preferred_language', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('farms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('gat_number', sa.String(length=100), nullable=True),
    sa.Column('area_hectares', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('village', sa.String(length=150), nullable=True),
    sa.Column('district', sa.String(length=150), nullable=True),
    sa.Column('state', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmer_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farms_farmer_id'), 'farms', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_farms_gat_number'), 'farms', ['gat_number'], unique=False)
    op.create_table('crops',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('crop_name', sa.String(length=150), nullable=False),
    sa.Column('variety', sa.String(length=150), nullable=True),
    sa.Column('sowing_date', sa.Date(), nullable=True),
    sa.Column('expected_harvest_date', sa.Date(), nullable=True),
    sa.Column('season', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crops_farm_id'), 'crops', ['farm_id'], unique=False)
    op.create_table('farm_boundaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id')
    )
    op.create_index(
        'idx_farm_boundaries_geometry',
        'farm_boundaries',
        ['geometry'],
        unique=False,
        postgresql_using='gist',
    )
    op.create_table('advisories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('crop_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advisories_crop_id'), 'advisories', ['crop_id'], unique=False)
    op.create_index(op.f('ix_advisories_farm_id'), 'advisories', ['farm_id'], unique=False)
    op.create_table('crop_observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('crop_id', sa.UUID(), nullable=False),
    sa.Column('observation_date', sa.Date(), nullable=False),
    sa.Column('data_source', sa.String(length=100), nullable=False),
    sa.Column('cloud_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_observations_crop_id'), 'crop_observations', ['crop_id'], unique=False)
    op.create_index(op.f('ix_crop_observations_observation_date'), 'crop_observations', ['observation_date'], unique=False)
    op.create_table('health_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('observation_id', sa.UUID(), nullable=False),
    sa.Column('metric_name', sa.String(length=50), nullable=False),
    sa.Column('metric_value', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('health_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['crop_observations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_metrics_observation_id'), 'health_metrics', ['observation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_health_metrics_observation_id'), table_name='health_metrics')
    op.drop_table('health_metrics')
    op.drop_index(op.f('ix_crop_observations_observation_date'), table_name='crop_observations')
    op.drop_index(op.f('ix_crop_observations_crop_id'), table_name='crop_observations')
    op.drop_table('crop_observations')
    op.drop_index(op.f('ix_advisories_farm_id'), table_name='advisories')
    op.drop_index(op.f('ix_advisories_crop_id'), table_name='advisories')
    op.drop_table('advisories')
    op.drop_index(
        'idx_farm_boundaries_geometry',
        table_name='farm_boundaries',
        postgresql_using='gist',
    )
    op.drop_table('farm_boundaries')
    op.drop_index(op.f('ix_crops_farm_id'), table_name='crops')
    op.drop_table('crops')
    op.drop_index(op.f('ix_farms_gat_number'), table_name='farms')
    op.drop_index(op.f('ix_farms_farmer_id'), table_name='farms')
    op.drop_table('farms')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('farmer_profiles')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
